### PR TITLE
Add the official soundtrack of branding jingles from 2020

### PR DESCRIPTION
**Pull request by omgmog**

### CODE REVIEW

**Comment by benfoxbotica** [comment]
My initial thought:

### OMG, DID @omgmog JUST DROP A NEW ALBUM!? … I can't wait to meet those beats 🎧 

…… listens to "album" …

# 🤦

**Comment by benfoxbotica** [comment]
This is awesome man.  (I'd expect nothing less from "Airquotes Biggest Fan")

**Review by benfoxbotica — APPROVED** [review]

**Comment by benfoxbotica** [comment]
Though actually, one change.  Could be better to remove spaces/punctuation from the file names?

That way we'd avoid urls like:

`/live/Airquotes%20The%20Podcast%20Airquotes%20-%20The%20Branding%20Album%20(2020)/Airquotes%20The%20Podcast%20Airquotes%20-%20The%20Branding%20Album%20-%2001%20-%20Episode%2016%20Intro.ogg

**Comment by omgmog** [comment]
> Though actually, one change. Could be better to remove spaces/punctuation from the file names?
> 
> That way we'd avoid urls like:
> 
> `/live/Airquotes%20The%20Podcast%20Airquotes%20-%20The%20Branding%20Album%20(2020)/Airquotes%20The%20Podcast%20Airquotes%20-%20The%20Branding%20Album%20-%2001%20-%20Episode%2016%20Intro.ogg

I guess we could go for a _scene style_ naming, rather than the verbose comedy naming (and ID3 tagging) I've gone for... 🤔

**Comment by omgmog** [comment]
Now you'll have for example:

> /live/Airquotes\_The\_Podcast\_Airquotes\_-\_The\_Branding\_Album\_2020/05\_-\_episode\_18\_end\_on\_a\_jingle\_(skit).ogg

**Pull request closed without merging**
